name: '@agaroot-technologies/merge-master'
description: 'Automatically merge master branch to the topic branch'
inputs:
  github-token:
    description: 'Github Token'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
